import json
articles = [
  {"id":"s1","universityName":"Harvard University","universityShortName":"Harvard","title":"Harvard Admits 3.6% to Class of 2029","url":"https://news.harvard.edu/gazette/","source":"Harvard Gazette","publishedAt":"2026-04-30T10:00:00Z","scrapedAt":"2026-05-02T10:00:00Z","summaryEn":"Harvard admitted 3.6% of applicants to the Class of 2029, one of the lowest rates in school history. The class spans all 50 states and 100+ countries, with 18% being first-generation college students.","summaryCn":"哈佛大学2029届录取率仅为3.6%，创历史新低。录取学生来自美国所有50个州和100多个国家，其中18%为家庭中第一代大学生。","category":"ADMISSIONS_STATS","urgency":"URGENT","urgencyReason":"Acceptance rate dropped significantly year-over-year."},
  {"id":"s2","universityName":"Massachusetts Institute of Technology","universityShortName":"MIT","title":"MIT Reinstates SAT/ACT Requirement for All Applicants","url":"https://news.mit.edu/","source":"MIT News","publishedAt":"2026-04-29T10:00:00Z","scrapedAt":"2026-05-02T10:00:00Z","summaryEn":"MIT reinstated its SAT/ACT requirement for all applicants, reversing the test-optional policy from COVID-19. Research confirmed standardized scores remain strong predictors of academic success at MIT.","summaryCn":"MIT恢复了SAT/ACT考试要求，撤销了新冠疫情期间的免考试政策。研究证实标准化考试成绩仍是预测MIT学业成功的重要指标。","category":"APPLICATION_POLICY","urgency":"URGENT","urgencyReason":"MIT reverting to test-required is a major policy change."},
  {"id":"s3","universityName":"Stanford University","universityShortName":"Stanford","title":"Stanford Releases Official AI Policy for Applications","url":"https://admission.stanford.edu/","source":"Stanford Admissions","publishedAt":"2026-05-01T10:00:00Z","scrapedAt":"2026-05-02T10:00:00Z","summaryEn":"Stanford released its official AI use policy for college applications. AI tools may help with brainstorming and editing, but all essays must authentically represent the applicant's own voice and ideas.","summaryCn":"斯坦福发布了申请中使用AI的官方政策。AI工具可用于头脑风暴和编辑，但所有文章必须真实代表申请者自己的声音和想法。","category":"AI_TECHNOLOGY","urgency":"URGENT","urgencyReason":"New AI policy affects how all students must prepare application materials."},
  {"id":"s4","universityName":"Yale University","universityShortName":"Yale","title":"Yale Expands Financial Aid to International Students","url":"https://your.yale.edu/","source":"Yale News","publishedAt":"2026-04-28T10:00:00Z","scrapedAt":"2026-05-02T10:00:00Z","summaryEn":"Yale expanded need-based financial aid for international undergraduates. Starting 2025-2026, international students qualify for the same need-blind admissions process as domestic applicants.","summaryCn":"耶鲁大学扩大了面向国际本科生的助学金项目。从2025-2026学年起，国际学生将享有与美国国内申请者相同的不看财务状况录取流程。","category":"INTERNATIONAL","urgency":"NORMAL"},
  {"id":"s5","universityName":"Duke University","universityShortName":"Duke","title":"Duke Updates ED Deadline and Extends Test-Flexible Policy","url":"https://admissions.duke.edu/","source":"Duke Admissions","publishedAt":"2026-05-01T10:00:00Z","scrapedAt":"2026-05-02T10:00:00Z","summaryEn":"Duke moved its ED I deadline from November 1 to November 3 for 2025-2026. Regular Decision stays January 4. Duke also confirmed test-flexible admissions continues for one more year.","summaryCn":"杜克大学将ED截止日期从11月1日调整至11月3日，常规决定截止日期仍为1月4日，并延续灵活考试政策一年。","category":"APPLICATION_POLICY","urgency":"URGENT","urgencyReason":"ED deadline change impacts student application planning."},
  {"id":"s6","universityName":"Columbia University","universityShortName":"Columbia","title":"Columbia Launches Quantum Computing Undergraduate Major","url":"https://engineering.columbia.edu/","source":"Columbia News","publishedAt":"2026-04-27T10:00:00Z","scrapedAt":"2026-05-02T10:00:00Z","summaryEn":"Columbia Engineering launched a new Quantum Computing undergraduate major, among the first in the Ivy League. The program draws from physics, computer science, and applied mathematics.","summaryCn":"哥伦比亚大学工程学院推出量子计算本科专业，是常青藤盟校中首批之一，结合物理、计算机科学和应用数学。","category":"POPULAR_MAJORS","urgency":"NORMAL"},
  {"id":"s7","universityName":"University of Pennsylvania","universityShortName":"UPenn","title":"Wharton Reports Record Chinese Student Applications","url":"https://www.wharton.upenn.edu/","source":"Penn Today","publishedAt":"2026-04-30T10:00:00Z","scrapedAt":"2026-05-02T10:00:00Z","summaryEn":"Wharton received record international applications for Class of 2029, with Chinese students forming the largest international pool. The school expanded Mandarin advising services in response.","summaryCn":"沃顿商学院收到创纪录的2029届国际学生申请，中国学生为最大国际申请群体，学校已扩大普通话辅导服务。","category":"INTERNATIONAL","urgency":"NORMAL"},
  {"id":"s8","universityName":"Johns Hopkins University","universityShortName":"JHU","title":"JHU Biomedical Engineering Ranked #1 for 15th Consecutive Year","url":"https://hub.jhu.edu/","source":"JHU Hub","publishedAt":"2026-04-26T10:00:00Z","scrapedAt":"2026-05-02T10:00:00Z","summaryEn":"Johns Hopkins Biomedical Engineering kept its #1 US News ranking for the 15th straight year. Applications rose 40% over three years driven by pre-med and biotech students.","summaryCn":"约翰斯·霍普金斯大学生物医学工程连续第15年位居美国新闻排名第一，过去三年申请人数增长40%。","category":"POPULAR_MAJORS","urgency":"NORMAL"},
  {"id":"s9","universityName":"Princeton University","universityShortName":"Princeton","title":"Princeton Adds 500 Paid Research Spots for Undergraduates","url":"https://www.princeton.edu/","source":"Princeton News","publishedAt":"2026-04-29T10:00:00Z","scrapedAt":"2026-05-02T10:00:00Z","summaryEn":"Princeton announced 500 new funded undergraduate research positions for fall 2025 in STEM fields. Students receive stipends and mentorship from Nobel laureate faculty.","summaryCn":"普林斯顿大学宣布2025年秋季新增500个有薪本科生STEM研究职位，学生将获得津贴并由诺贝尔奖得主教师指导。","category":"EXTRACURRICULAR","urgency":"NORMAL"},
  {"id":"s10","universityName":"University of California Los Angeles","universityShortName":"UCLA","title":"UCLA Overhauls Transfer Admissions with Holistic Review","url":"https://admission.ucla.edu/","source":"UCLA Newsroom","publishedAt":"2026-04-28T10:00:00Z","scrapedAt":"2026-05-02T10:00:00Z","summaryEn":"UCLA introduced holistic review for transfer applicants from 2025-2026, prioritizing personal essays, community college leadership, and academic resilience over GPA alone.","summaryCn":"UCLA推出2025-2026年转学生全面审核制度，优先考量个人文章、社区大学领导力和学业韧性，而非单纯依靠GPA。","category":"APPLICATION_POLICY","urgency":"NORMAL"}
]
with open("data/news-store.json","w") as f:
    json.dump(articles,f,indent=2)
print("Done! 10 articles written.")
