import { NewsArticle, AppConfig, CATEGORY_LABELS, NewsCategory } from './types'

interface EmailPayload {
  to: string[]
  subject: string
  html: string
}

async function getTransporter(config: AppConfig) {
  const nodemailer = await import('nodemailer')
  return nodemailer.default.createTransport({
    host: config.smtpHost,
    port: config.smtpPort,
    secure: config.smtpPort === 465,
    auth: {
      user: config.smtpUser,
      pass: config.smtpPass,
    },
  })
}

async function sendEmail(payload: EmailPayload, config: AppConfig): Promise<void> {
  if (!config.smtpUser || !config.smtpPass) {
    throw new Error('SMTP credentials not configured. Please set them in Settings.')
  }
  if (!payload.to.length) {
    throw new Error('No recipients configured. Please add recipients in Settings.')
  }

  const transporter = await getTransporter(config)
  await transporter.sendMail({
    from: `"University News Watcher" <${config.smtpUser}>`,
    to: payload.to.join(', '),
    subject: payload.subject,
    html: payload.html,
  })
}

// ── Email Templates ───────────────────────────────────────────────────────────

function emailWrapper(title: string, body: string): string {
  return `
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${title}</title>
<style>
  body { margin: 0; padding: 0; background: #f5f3ee; font-family: Georgia, 'Times New Roman', serif; color: #0a0a0f; }
  .wrapper { max-width: 680px; margin: 0 auto; padding: 32px 16px; }
  .header { background: #0a0a0f; color: #f5f3ee; padding: 24px 32px; border-radius: 4px 4px 0 0; }
  .header h1 { margin: 0; font-size: 20px; font-weight: normal; letter-spacing: 0.05em; }
  .header p { margin: 4px 0 0; font-size: 13px; opacity: 0.6; font-family: monospace; }
  .content { background: white; padding: 32px; border-radius: 0 0 4px 4px; border: 1px solid #ede9e0; border-top: none; }
  .section-title { font-size: 11px; font-weight: bold; letter-spacing: 0.15em; text-transform: uppercase; color: #666; border-bottom: 1px solid #ede9e0; padding-bottom: 8px; margin: 32px 0 16px; }
  .article { padding: 16px 0; border-bottom: 1px solid #f5f3ee; }
  .article:last-child { border-bottom: none; }
  .article-uni { font-size: 11px; text-transform: uppercase; letter-spacing: 0.1em; color: #999; margin-bottom: 4px; }
  .article-title { font-size: 16px; font-weight: bold; margin: 0 0 8px; }
  .article-title a { color: #0a0a0f; text-decoration: none; }
  .article-title a:hover { text-decoration: underline; }
  .article-summary { font-size: 14px; line-height: 1.6; color: #444; margin: 0 0 8px; }
  .article-meta { font-size: 12px; color: #999; font-family: monospace; }
  .urgent-banner { background: #c0392b; color: white; padding: 12px 16px; border-radius: 4px; margin-bottom: 8px; }
  .urgent-banner strong { display: block; font-size: 11px; letter-spacing: 0.1em; text-transform: uppercase; }
  .urgent-banner p { margin: 4px 0 0; font-size: 13px; }
  .badge { display: inline-block; font-size: 10px; padding: 2px 8px; border-radius: 2px; font-family: monospace; letter-spacing: 0.05em; background: #f0f2f5; color: #555; margin-right: 8px; }
  .footer { text-align: center; font-size: 12px; color: #999; margin-top: 24px; font-family: monospace; }
</style>
</head>
<body>
<div class="wrapper">
  <div class="header">
    <h1>University News Watcher</h1>
    <p>${title}</p>
  </div>
  <div class="content">
    ${body}
  </div>
  <div class="footer">
    Generated by University News Watcher · ${new Date().toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}
  </div>
</div>
</body>
</html>`
}

function articleHTML(article: NewsArticle, lang: 'en' | 'cn' = 'en'): string {
  const summary = lang === 'cn' ? article.summaryCn : article.summaryEn
  const source = article.source
  const date = new Date(article.scrapedAt).toLocaleDateString('en-US', { month: 'short', day: 'numeric' })

  return `
<div class="article">
  <div class="article-uni">${article.universityShortName}</div>
  <div class="article-title"><a href="${article.url}" target="_blank">${article.title}</a></div>
  <p class="article-summary">${summary}</p>
  <div class="article-meta">
    <span class="badge">${CATEGORY_LABELS[article.category]?.[lang] || article.category}</span>
    ${source} · ${date}
  </div>
</div>`
}

// ── Weekly Digest Email ───────────────────────────────────────────────────────

export async function sendWeeklyDigest(
  articles: NewsArticle[],
  config: AppConfig
): Promise<void> {
  if (!config.weeklyDigestEnabled) return

  const lang = config.defaultLanguage
  const dateRange = (() => {
    const end = new Date()
    const start = new Date()
    start.setDate(start.getDate() - 7)
    return `${start.toLocaleDateString('en-US', { month: 'short', day: 'numeric' })} – ${end.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}`
  })()

  const categoryOrder: NewsCategory[] = [
    'APPLICATION_POLICY', 'ADMISSIONS_STATS', 'POPULAR_MAJORS',
    'EXTRACURRICULAR', 'AI_TECHNOLOGY', 'INTERNATIONAL', 'OTHER_MARKETS', 'GENERAL'
  ]

  // Urgent first
  const urgentArticles = articles.filter((a) => a.urgency === 'URGENT')
  let body = ''

  if (urgentArticles.length > 0) {
    body += `<div class="section-title">🚨 Urgent Alerts</div>`
    body += urgentArticles.map((a) => articleHTML(a, lang)).join('')
  }

  // Then by category
  for (const cat of categoryOrder) {
    const catArticles = articles.filter((a) => a.category === cat && a.urgency !== 'URGENT')
    if (catArticles.length === 0) continue
    const label = CATEGORY_LABELS[cat]?.[lang] || cat
    body += `<div class="section-title">${label}</div>`
    body += catArticles.map((a) => articleHTML(a, lang)).join('')
  }

  if (!body) {
    body = '<p style="color:#999;text-align:center;">No articles found this week.</p>'
  }

  const subject = `Weekly University Admissions Digest — ${dateRange}`
  const html = emailWrapper(subject, body)

  await sendEmail({ to: config.recipients, subject, html }, config)
  console.log(`✅ Weekly digest sent to ${config.recipients.join(', ')}`)
}

// ── Urgent Alert Email ────────────────────────────────────────────────────────

export async function sendUrgentAlert(
  article: NewsArticle,
  config: AppConfig
): Promise<void> {
  if (!config.urgentAlertsEnabled) return

  const lang = config.defaultLanguage
  const summary = lang === 'cn' ? article.summaryCn : article.summaryEn

  const body = `
<div class="urgent-banner">
  <strong>🚨 Urgent Admissions Alert</strong>
  <p>${article.urgencyReason || 'This article has been flagged as urgent.'}</p>
</div>
<div class="article">
  <div class="article-uni">${article.universityName}</div>
  <div class="article-title"><a href="${article.url}">${article.title}</a></div>
  <p class="article-summary">${summary}</p>
  <div class="article-meta">
    Source: ${article.source} · ${new Date(article.scrapedAt).toLocaleString()}
  </div>
</div>`

  const subject = `URGENT: ${article.universityShortName} — ${article.title.slice(0, 60)}`
  const html = emailWrapper(subject, body)

  await sendEmail({ to: config.recipients, subject, html }, config)
  console.log(`✅ Urgent alert sent: ${article.title.slice(0, 60)}`)
}
